### ISSUE TITLE
Modifier la couleur des liens hypertexte dans le texte

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/utilitr-template#18]
La couleur des liens hypertexte (#3C5C5C) dans le texte du site `bs4` est trop proche du noir, ce qui fait qu'on ne repère pas les liens.

On pourrait ajouter `main a[href] {color: à définir;}` dans `customize-bs4.css`, de façon à ne pas modifier les deux barres de navigation (pour lesquelles la couleur existante me semble OK car elles ne sont constitués que de liens hypertexte par définition). Attention, il faut s'assurer que le print ne devient pas trop moche. Normalement ça ne touche pas le pdf `pagedown` qui utilise d'autres CSS.

Et au fait @RLesur et @linogaliana , revoilà une _issue_ dans le dépôt.

**Comment by oliviermeslin** [comment]
Réglé par #17

**Comment by linogaliana** [comment]
je l'avais même pas vue
